application/account/urls.py
from django.conf.urls import patterns, include, url
import views


urlpatterns = patterns('',
    url(r'^login/$', 
        views.LoginView.as_view(), 
        name='login'
    ),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^create_user/', 
        views.CreateUserView.as_view(), 
        name='create-user'
    )
)

hla_task/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', 'application.public.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^account/', include('application.account.urls', namespace='account'))
)

application/account/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    ROLES = (
        ('manager', 'Manager'),
        ('developer', 'Developer'),
        ('customer', 'Customer'),
        ('qa_enginer', 'Qa enginer'),
        ('reporter', 'Reporter')
    )

    role = models.SlugField(default='developer', choices=ROLES)

application/core/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _

class Image(models.Model):
    image = models.FileField(upload_to='static/account', verbose_name=_('Image'))

application/account/forms.py
from django import forms
from models import User
from django.contrib import auth
from django.utils.translation import ugettext_lazy as _


class LoginForm(forms.Form):
    """
    Form for login
    """
    username = forms.CharField(widget=forms.TextInput(
        attrs = {
            'placeholder': _('username')
        }
    ))
    password = forms.CharField(widget=forms.PasswordInput(
        attrs = {
            'placeholder': _('password')
        }
    ))

    def __init__(self, request, *args, **kwargs):
        super(LoginForm, self).__init__(*args, **kwargs)
        self.request = request

    def clean(self):
        cleaned_data = super(LoginForm, self).clean()
        username = cleaned_data.get('username')
        password = self.cleaned_data.get('password')
        user = auth.authenticate(username=username, password=password)

        if not user:
            raise forms.ValidationError(_('User is not authenticated'))
        auth.login(self.request, user)
        return cleaned_data
        

class CreateUserForm(forms.ModelForm):

    username = forms.CharField(widget=forms.TextInput(
        attrs = {
            'placeholder': _('username')
        }
    ))

    class Meta:
        model = User
        fields = ['username', 'email', 'role']
    
    def __init__(self, *args, **kwargs):
        self.base_fields['username'].help_text = None
        for key in self.base_fields:
            self.base_fields[key].label = ''
            self.base_fields[key].placeholder = key
        super(CreateUserForm, self).__init__(*args, **kwargs)

application/account/views.py
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse
from django.views.generic.edit import FormView, CreateView
from django.views.generic import TemplateView
from django.contrib import auth
from django.http import HttpResponseRedirect

from .models import User
from .forms import LoginForm, CreateUserForm


class LoginView(FormView):

    form_class = LoginForm
    success_url = '/'
    template_name = 'account/login.html'

    def get_form_kwargs(self):
        form_kwargs = super(LoginView, self).get_form_kwargs()
        form_kwargs.update({
            'request': self.request
        })
        return form_kwargs

    def form_valid(self, form):
        return redirect(self.get_success_url())

class UserProfileView():
    pass


class CreateUserView(CreateView):
    """
    Create new user
    """
    form_class = CreateUserForm
    model = User
    success_url = '/'
    template_name = 'account/create_user.html'

    def form_valid(self, form):
        super(CreateUserView, self).form_valid(form)
        return redirect(self.get_success_url())


def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('account:login'))

application/core/views.py
from django.shortcuts import render

# Create your views here.

templates/base.html
{% load staticfiles %}
<html>
    <head>
        <meta charset="utf-8">
        <title>Hla task</title>
        <link href="{% static 'css/style.css' %}" rel="stylesheet">
    </head>
    <body>
        <div id="wrapper" class="content">
            <header>
                <div class="banner">
                    <h1><a href="{% url 'home' %}">Hla task</a></h1>
                    <div class="sign">
                        {% if user.is_authenticated %}
                        <div class="account">
                            <div class="u-name">
                                <img src="{% static 'uploads/happy-icon.png' %}">
                                <a href="{% url 'home' %}">{{ user }}</a>
                            </div>
                            <div class="head-dropdown">
                                <div><a>Edit Profile</a></div>
                                <div><a>Projects</a></div>
                                <div><a>Teams</a></div>
                                <div>
                                    <a href="{% url 'account:logout' %}">Logout</a>
                                </div>
                            </div>
                        </div>
                        {% endif %}
                    </div>
                </div>
            </header>
            <div id="main">
                {% block main %}
                {% endblock %}
            </div>
            <footer>
            <div class="copy">
                &copy Hla core team
            </div>
            </footer>
        </div>
        <script src="{% static 'components/jquery/jquery.min.js' %}"></script>
        <script src="{% static 'components/handlebars/handlebars.min.js' %}" type="text/javascript" ></script>
        <script src="{% static 'components/ember/ember.min.js' %}" type="text/javascript"></script>
        <script src="{% static 'components/ember-data/ember-data.min.js' %}" type="text/javascript"></script>
        <script src="{% static 'js/models.js' %}"></script>
        <script src="{% static 'js/app.js' %}" type="text/javascript"></script>
    </body>
</html